version: '3.8'

services:
  frontend:
    build: .
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NODE_ENV: production

  backend:
    build: .././backend
    volumes:
      - .././backend:/app
    ports:
      - '5001:5000' # External port 5001 maps to internal port 5000
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: apartments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      NODE_ENV: production

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apartments_db
    ports:
      - '5433:5432' # External port 5433 maps to internal port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
