services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: apartments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      NODE_ENV: production

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apartments_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
